version: "3.8"
services:
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 1111:8000
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: fastapi_db
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev



volumes:
  pgdata: