version: "3.8"
services:

  db:
    restart: always
    image: postgres:15-alpine
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    networks:
      - backend


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 1111:8000
    depends_on:
      - db
    networks:
      - backend


networks:
  backend:
    driver: bridge






