"""migration3

Revision ID: 90d5df622068
Revises: 9d08bf4e224f
Create Date: 2023-09-20 15:17:26.966955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d5df622068'
down_revision: Union[str, None] = '9d08bf4e224f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_models_data', sa.Column('date_of_creation', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_models_data', 'date_of_creation')
    # ### end Alembic commands ###
