"""migration1

Revision ID: 9d08bf4e224f
Revises: 820a77f9508b
Create Date: 2023-09-19 15:06:22.966178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d08bf4e224f'
down_revision: Union[str, None] = '820a77f9508b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_models_data',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_model', sa.String(), nullable=False),
    sa.Column('car_height', sa.Float(), nullable=False),
    sa.Column('car_width', sa.Float(), nullable=False),
    sa.Column('car_length', sa.Float(), nullable=False),
    sa.Column('car_speed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('owner_data',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('registration_address', sa.String(), nullable=False),
    sa.Column('actual_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('tech_passport_data',
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.String(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('date_of_issue', sa.Date(), nullable=False),
    sa.Column('car_color', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car_models_data.car_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner_data.owner_id'], ),
    sa.PrimaryKeyConstraint('passport_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_passport_data')
    op.drop_table('owner_data')
    op.drop_table('car_models_data')
    # ### end Alembic commands ###
